export const LOCAL_STORAGE_KEYS = {
    USER_TOKEN: 'USER_TOKEN',
    CITY: 'CITY',
    DATE_TYPE: 'DATE_TYPE',
    START_DATE: 'START_DATE',
    END_DATE: 'END_DATE',
    MAP_TYPE: 'MAP_TYPE',
    EVENT_TYPES: 'EVENT_TYPES',
    PLACE_TYPES: 'PLACE_TYPES',
    FAVORITE_EVENTS: 'FAVORITE_EVENTS',
    FAVORITE_PLACES: 'FAVORITE_PLACES',
};